# Generated by Django 6.1 on 2026-08-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('typical_cycle_days', models.PositiveIntegerField(blank=True, help_text='Typical duration from sowing to harvest in days', null=True)),
                ('expected_yield_per_acre', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield per acre (in your preferred unit, e.g., kg or tons)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Farmer who owns this crop catalog entry', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'variety')},
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(help_text='e.g., Kharif, Rabi, Summer', max_length=50)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('growth_stage', models.CharField(choices=[('Planned', 'Planned'), ('Sown', 'Sown'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Fruiting', 'Fruiting'), ('Harvesting', 'Harvesting'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Planned', max_length=20)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Expected total yield for this plot', max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Actual total yield for this plot', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cycles', to='crops.crop')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='plots.plot')),
            ],
            options={
                'ordering': ['-sowing_date'],
            },
        ),
    ]
