# Generated by Django 6.1 on 2026-08-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity harvested', max_digits=10)),
                ('grade_or_quality', models.CharField(blank=True, help_text='e.g., Grade A, Premium, Regular', max_length=100, null=True)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture % (if applicable)', max_digits=5, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='crops.cropcycle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
